services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_llama3
    volumes:
      - n:/ollama/llama3:/models
    environment:
      - MODEL_NAME=llama3
    command: ["start"]
    ports:
      - "11434:11434"  # Cambia este puerto para que coincida con el puerto correcto

  streamlit:
    build: .
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/predict
