version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_llama3
    environment:
      - MODEL_NAME=llama3
      - LOG_LEVEL=DEBUG 
    command: ["start"]
    ports:
      - "11434:11434"

  streamlit:
    build: .
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
